### ISSUE TITLE
FF00FF is not reachable with this map

### ISSUE THREAD

**Issue by Jonaseben** [pudquick/pyMCdyes#2]
Sorry, I don't know where I should put this issue to.

Why I cannot calculate this color "FF00FF"? Is it possible to expand the map?

**Comment by pudquick** [comment]
Sorry, no it's not.

Think of it this way: Adding one or more original game dyes "pulls" the color of your item towards the dye's color.

All of the dye colors in Minecraft represent the "extreme" / maximum color points you can "pull" your item's color towards.

The 3D shape here is a map of all the maximum colors in RGB:

http://pudquick.github.io/pyMCdyes/images/views.png

Every point on that shape is a dye. The insides of the shape represent all the places you can "pull" your item's color towards.

You can't "pull" towards FF00FF because its an extreme point - it's outside of that shape. There's no dye that can "pull" your item's color in that direction.

**Comment by Jonaseben** [comment]
Thanks, now I understand. Great support for great tools!:)
